-- AlterEnum
ALTER TYPE "TipoNotificacion" ADD VALUE 'PARTICIPANTE_APROBADO' AFTER 'SISTEMA';
ALTER TYPE "TipoNotificacion" ADD VALUE 'PARTICIPANTE_RECHAZADO' AFTER 'PARTICIPANTE_APROBADO';
ALTER TYPE "TipoNotificacion" ADD VALUE 'CERTIFICADO_EMITIDO' AFTER 'PARTICIPANTE_RECHAZADO';